# Numpy数组的计算：通用函数

***通用函数：ufunc***

## 1. Why ufunc?

In [2]:
import numpy as np
np.random.seed(0)

def compute(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
compute(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [6]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute(big_array)

1.46 s ± 14.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


**It's too slow!**

## 2. 通用函数介绍

**方便、静态类型、可编译程序的接口，也被称为向量操作**

In [8]:
print(compute(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [9]:
%timeit (1.0 / big_array)

1.28 ms ± 13.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


**quicker than compute function!!!**

In [11]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

**多维数组运算**

In [13]:
x = np.arange(9).reshape((3, 3))
2**x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

## 3. 探索Numpy的通用函数

**一元通用函数(unary ufunc)对单个输入操作  
二元通用函数(binary ufunc)对两个输入操作**

### 3.1 采用python标准计算符对数组内每一个值进行相同操作

In [17]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x+5)
print("x - 5 =", x-5)
print("x * 2 =", x*2)
print("x / 2 =", x/2)
print("x // 2 =", x//2)

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [18]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

|运算符|对应的ufunc|
|-----|----------|
|+|np.add|
|-|np.substract|
|-|np.negative|
|\*|np.multiply|
|/|np.divide|
|//|np.floor_divide|
|**|np.power|
|%|np.mod|


In [21]:
np.negative(x)

array([ 0, -1, -2, -3])

In [22]:
np.power(x, 5)

array([  0,   1,  32, 243])

In [23]:
np.power(5, x)

array([  1,   5,  25, 125])

### 3.2 三种绝对值调用方法

In [24]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [25]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [26]:
np.abs(x)

array([2, 1, 0, 1, 2])

处理复数时绝对值返回该复数的幅度,dtype=float

In [28]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

### 3.3 三角函数

np.linspace(start, stop, sample_number)

In [29]:
theta = np.linspace(0, np.pi, 3)

In [36]:
print("theta = ", '0'.ljust(10), 'pi/2'.rjust(10), 'pi'.rjust(10))
print("theta = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta =  0                pi/2         pi
theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [38]:
x = [-1, 0, 1]
print("x = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


### 3.4 指数和对数

In [43]:
x = [1, 2, 3]
print("x = ", x)
print("e^x = ", np.exp(x))
print("2^x = ", np.exp2(x))  # exp2得到的值为float
print("3^x = ", np.power(3, x))  # power得到的值为int

x =  [1, 2, 3]
e^x =  [ 2.71828183  7.3890561  20.08553692]
2^x =  [2. 4. 8.]
3^x =  [ 3  9 27]


In [45]:
x = [1, 2, 4, 10]
print("x = ", x)
print("ln(x) = ", np.log(x))
print("log2(x) = ", np.log2(x))
print("log10(x) = ", np.log10(x))

x =  [1, 2, 4, 10]
ln(x) =  [0.         0.69314718 1.38629436 2.30258509]
log2(x) =  [0.         1.         2.         3.32192809]
log10(x) =  [0.         0.30103    0.60205999 1.        ]


### 3.5 专用的通用函数

**[1.见Numpy文档](https://numpy.org/doc/1.20/user/quickstart.html)**  
**2.scipy.special类中包含大量高阶数学函数，如Gamma函数，相关函数，误差函数erf**

## 4. 高级的通用函数特性

### 4.1 指定输出

**大量计算时，通常指定一个用于存放运算结果的数组**

In [52]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


将计算结果写入指定数组每隔一个元素的位置

In [53]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


### 4.2 聚合

reduce方法会对给定元素和操作重复执行，直到得到单个结果

In [57]:
x = np.arange(1, 6)
print(x)
np.add.reduce(x)

[1 2 3 4 5]


15

In [58]:
print(x)
np.multiply.reduce(x)

[1 2 3 4 5]


120

如果你需要存储每次计算的中间结果，用accumulate

In [59]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [60]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

### 4.3 外积

使用outer方法可以获得两个不同的输入数组所有元素对的函数运算结果  
你可以用outer实现一个乘法表

In [62]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])