# 结构化数据：Numpy的结构化数组

In [20]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

**It's stupid and terrible!**

In [21]:
import numpy as np 
# 使用复合数据结构的结构化数组
data = np.zeros(4, dtype={'names': ('name', 'age', 'weight'), 'formats': ('U10', 'i4', 'f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


'U10'表示长度不超过10的Unicode字符串  
'i4'表示4字节整型  
'f8'表示8字节浮点型

In [22]:
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [23]:
# 获取所有名字
data['name']

array(['Alice', 'Bob', 'Cathy', 'Doug'], dtype='<U10')

In [24]:
# 获取数据第一行
data[0]

('Alice', 25, 55.)

In [25]:
# 获取最后一行的名字
data[-1]['name']

'Doug'

利用布尔掩码，可以做一些复杂的操作，如按照年龄筛选

In [26]:
data[data['age'] < 30]['name']

array(['Alice', 'Doug'], dtype='<U10')

## 1.生成结构化数组

In [27]:
np.dtype({'names': ('name', 'age', 'weight'), 
'formats': ('U10', 'i4', 'f8')})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

或者将数值类型用python类型或Numpy的dtype类型表示

In [28]:
np.dtype({'names': ('name', 'age', 'weight'), 
          'formats': ((np.str_, 10), int, np.float32)})

dtype([('name', '<U10'), ('age', '<i8'), ('weight', '<f4')])

**复合类型也可以写成元组列表形式**

In [29]:
np.dtype([('name', 'S10'), ('age', 'i4'), ('weight', 'f8')])

dtype([('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])

**忽略类型的名称，用一个字符串表示**

In [30]:
np.dtype('S10, i4, f8')

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

## 2.更高级的复合类型

In [31]:
tp = np.dtype([('id', 'i8'), ('mat', 'f8', (3, 3))])
x = np.zeros(1, dtype=tp)
print(x[0])
print(x['mat'][0])

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
